blog/urls.py
from django.urls import path, re_path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    re_path(r'tag/(?P<tag_slug>[-\w]+)/', views.post_list, name='post_list_by_tag'),
    re_path(r'detail/(?P<post>[-\w]+)/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

simple_full/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _
from taggit.managers import TaggableManager
from extensions.utils import jalali_converter


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(_('اسم'), max_length=250)
    slug = models.SlugField(max_length=250, allow_unicode=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_pots')
    objects = models.Manager()  # the default manager
    published = PublishedManager()  # custom manager
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_converter(self.publish)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(_('نام'), max_length=80)
    email = models.EmailField(_('ایمیل'))
    body = models.TextField(_('متن'))
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),

        ]

    def __str__(self):
        return f'comments by {self.name} on {self.post}'

    def jpublish(self):
        return jalali_converter(self.created)

blog/forms.py
from django import forms
from django.forms import EmailInput, TextInput, Textarea

from .models import Comment
from django.utils.translation import gettext as _


class EmilPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(
        attrs={'placeholder': 'نام شما', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'ایمیل فرستنده', 'class': 'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'ایمیل گیرنده ', 'class': 'form-control'}))
    comments = forms.CharField(required=False,
                               widget=forms.Textarea(attrs={'placeholder': 'نظر شما در  مورد این پست '}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            'name': TextInput(attrs={
                'style': 'width: 300px;',
                'class': "form-control",
                'placeholder': 'نام'
            }),
            'email': EmailInput(attrs={
                'style': 'width: 300px;',
                'class': "form-control text-center",
                'placeholder': 'ایمیل'
            }),
            'body': Textarea(attrs={
                'style': 'width: 300px;',
                'class': "form-control",
                'placeholder': 'متن نظر شما'
            }),
        }


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank
from .forms import EmilPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count


# Create your views here.
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination with 3 posts pre page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html',
                  {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmilPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} پیشنها میدهد {post.title} را بخوانید "
            message = f"این مطلب {post.title} در این ادرس بخوان {post_url}\n\n {cd['name']}  نظرش: {cd['comments']} "
            send_mail(subject, message, 'work.moshavereh@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmilPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(search=search_vector,rank=SearchRank(search_vector,search_query)).filter(search=search_query).order_by('-rank')
            results = Post.published.annotate(search=SearchVector('title', 'body'), ).filter(search=query)
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel="stylesheet" type="text/css"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">مشاوره با ما</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">خانه</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">مقالات</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">صفحات مجازی</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">تماس با ما </a></li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'assets/img/home.png' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>مشاوره باما</h1>
                    <span class="subheading">به مشاوره با ما خوش امدید</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">

    <div class="row gx-4 gx-lg-5 justify-content-center">
        {% block sidebar %}

        {% endblock %}
        <div class="col-md-10 col-lg-8 col-xl-7">

            {% block content %}

            {% endblock %}

        </div>

    </div>

</div>

<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/blog/post/comment.html
{% extends 'blog/base.html' %}
{% block title %}
    اضافه کردن نظر
{% endblock %}
{% block content %}
    {% if comment %}
        <h2>کامنت شما با موفقیت ثبت شد</h2>
        <p><a href="{{ post.get_absolute_url }}">برگشت به مقاله </a></p>
    {% else %}
        {% include 'blog/post/includes/comment_form.html' %}
    {% endif %}
{% endblock %}

templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load social_share %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
     <!--- Post body section --->
    <h1>{{ post.title }}</h1>
    <p class="post-meta">
        منتشر شده توسط {{ post.author }} در تاریخ {{ post.jpublish }}
    </p>
    <p>{{ post.body|markdown }}</p>
   <!--- Post share section --->
    <div class="dropdown p-5">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">به اشتراک گذاری این پست
            <span class="caret"></span></button>
        <ul class="dropdown-menu justify-content-center">
            <li class="p-2">
                <a href="#"><span class="nav-item">
            {% post_to_telegram 'تلگرام {{ post.title }}' object_or_url '<i class="fa-brands fa-telegram fa-2x"></i>' %}
            </span></a></li>
            <li class="p-2">
                <a href="#">
                        <span class="nav-item">{% post_to_whatsapp 'واتس اپ {{ post.title }}' '<i class="fa-brands fa-whatsapp fa-2x"></i>' %}
                        </span>
                </a>
            </li>
            <li class="p-2">
                <a href="{% url 'blog:post_share' post.id %}">
                    اشراک گذاری با ایمیل
                </a>
            </li>
        </ul>
    </div>
     <!--- Post similar section --->
    <div class="card mb-4">
        <div class="card-header">مقالات مشابه</div>
        <div class="card-body">
            <div class="row">
                {% for post in similar_posts %}
                    <p>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </p>
                {% empty %}
                    پست و مقاله ای شبیه به این پست در حال حاضر در سایت وجود ندارد
                {% endfor %}
            </div>
        </div>
    </div>
     <!--- Post comment section --->
    <div class="card mb-4 container">
        {% with comments.count as total_comments %}
            <div class="card-header"> {{ total_comments }} نظر</div>
        {% endwith %}
        {% for comment in comments %}
            <div class="card-body">

            <p> نظر{{ forloop.counter }} توسط {{ comment.name }}
                {{ comment.jpublish }}
            </p>
            <p>
                {{ comment.body|linebreaks }}
            </p>

        {% empty %}
            <p> نظری وجود ندارد </p>
        {% endfor %}
        </div>

    </div>
    {% include "blog/post/includes/comment_form.html" %}

{% endblock %}

templates/blog/post/includes/comment_form.html
<div class="card-header"><h2>ثبت نظر </h2></div>
 <div class="container m-3">
    <form action="{% url 'blog:post_comment' post.id %}" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input class="btn btn-success" type="submit" value="ارسال نظر"></p>
    </form>
</div>

templates/blog/post/latest_posts.html
<ul  class="list-unstyled mb-0">
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
    My blog
{% endblock %}
{% block sidebar %}
    <div class="col-lg-4">
        {#                <!-- Search widget-->#}
        {#                <div class="card mb-4">#}
        {#                    <div class="card-header">Search</div>#}
        {#                    <div class="card-body">#}
        {#                        <div class="input-group">#}
        {#                            <input class="form-control" type="text" placeholder="Enter search term..."#}
        {#                                   aria-label="Enter search term..." aria-describedby="button-search"/>#}
        {#                            <button class="btn btn-primary" id="button-search" type="button">Go!</button>#}
        {#                        </div>#}
        {#                    </div>#}
        {#                </div>#}
        <!-- Categories widget-->
        <div class="card mb-4">
            <div class="card-header">ابزار ها</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-0">
                            <li>
                                <a href="{% url "blog:post_feed" %}">
                                    فید خبری ما
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'blog:post_search' %}">جست و جو در سایت </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Side widget-->
        <div class="card mb-4">
            <div class="card-header">اطلاعیه ها</div>
            <div class="card-body">
                <p>
                    تعداد پست و مقالات موجود: {% total_posts %}
                </p>
                <h3>اخرین مقالات و پست های اضافه شده به سایت
                </h3>
                <ul class="list-unstyled mb-0">
                    <li>
                        {% show_latest_posts 3 %}
                    </li>
                </ul>
                <h3>مقالات داری بیشترین نظر</h3>
                {% get_most_commented_post as most_commented_posts %}
                <ul class="list-unstyled mb-0">
                    {% for post in most_commented_posts %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <h1 class="post-title">مقلات و پست های ما </h1>
    <hr class="my-4"/>
    {% if tag %}
        <h2> تگ های این مقاله"{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <div class="post-preview">
        <h2 class="post-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
        <p class="datetime">
            تگ ها :
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %},{% endif %}
            {% endfor %}

        </p>
        <p class="post-meta">
            {{ post.author }} در منتشر شده توسط {{ post.jpublish }}
        </p>
        <p>
            {{ post.body|markdown|truncatewords_html:30 }}
        </p>
        <hr class="my-4"/>
    {% endfor %}
{% include 'paginator.html' with page=posts %}
</div>
{% endblock %}

templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% block title %}جست و جو{% endblock %}
{% block content %}
    <div class="my-5">
        {% if query %}
            <h1> مقالات حاوی " {{ query }}"</h1>
            <h3>
                {% with results.count as total_results %}
                    پیدا شده {{ total_results }} نتیجه
                {% endwith %}
            </h3>
            {% for post in results %}
                <h4>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h4>
                {{ post.body|truncatewords_html:12 }}
            {% empty %}
                <p>جست و جو نتیجه ای نداشت </p>
            {% endfor %}
            <p><a href="{% url "blog:post_search" %}">جست و جو مجدد </a></p>
        {% else %}
            <h1>جست و جو برای مقالات</h1>
            <form id="contactForm" method="get">
                {{ form.as_p }}
                <input type="submit" value="جست و جو">
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}
    اشتراک گذاری این پست
{% endblock %}
{% block content %}
    <div class="my-5">
        {% if sent %}
            <h1>ایمیل شما با موفقیت ارسال شد </h1>
            <p>"{{ post.title }}" با موفقیت ارسال شده به {{ form.cleaned_data.to }}</p>
        {% else %}
            <div class="container m-3">
                <h1 class="p-5">به اشتراک گذاری {{ post.title }} از طریق ایمیل </h1>
                <form id="contactForm" method="post">
                    <div class="form-floating">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <input class="btn btn-primary" type="submit" value="ارسال " role="button">
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/paginator.html
<div class="d-flex justify-content-end mb-4">
<span class="p-3">
 صفحه  {{ page.number }} از {{ page.paginator.num_pages }}
 </span>
    {% if page.has_previous %}
        <a class="btn btn-primary " href="?page={{ page.previous_page_number }}">
            مقلات جدیدتر
            →</a>
    {% endif %}

    {% if page.has_next %}
        <a class="btn btn-primary " href="?page={{ page.next_page_number }}">
            مقالات قدیمی تر
            →</a>
    {% endif %}

</div>